### PR TITLE
[ BB2-1180 ] Prep needed to Publish

### PR DESCRIPTION
**Pull request by dtisza1**
**JIRA Ticket:**
[BB2-1180](https://jira.cms.gov/browse/BB2-1180)

**User Story or Bug Summary:**

Python SDK: All Prep needed to Publish Python SDK

The SDK package is published on the TestPyPI site at:  https://test.pypi.org/project/cms-bluebutton-sdk

Please review this in addition to this PR. Thank you!

### What Does This PR Do?

The following is a summary of changes made:

- Change virtual environment dir name from bb2_env to bb2_venv

- Remove the un-needed MANIFEST.in

- Add a `.coveragerc` file to resolve issues with coverage.

- Update `setup.py`:
  - Change the package name from `cms_bluebutton` to `cms-bluebutton-sdk` for consistency with Node SDK.
  - Add `requests-toolbelt` dependency.
  - Add `requests-mock` dependency for the DEV extra requirements.

- Update `README-sdk-dev.md`:
  - Remove "$" from command lines so they can be easily copy&pasted.
  - Update Python virtual envirnoment instruction.
  - Update packages install instruction.
  - Remove Manifest instruction, since it is not needed.
  - Remove build instruction except for the `bdist_wheel` type of build.
  - Add instruction for: "Publish Testing using the TestPyPI registry instance"
  - Add instruction for "Publish to the main PyPI registry" based on previous TestPyPI working instruction. Note that this may need updated later.
  - Add instruction for next release.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check these things, in particular:

- Does this work for you locally? Testing the upload to TestPyPI is optional.
- If testing uploads, only upload to the TestPyPI registry site for now.
- Do the README instructions need improvement?
- Does the package look good published to the TestPyPI site?

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

- If the answer to any of the questions below is **Yes**, then here's a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence: N/A.
  - Does this PR add any new software dependencies?  **No**.
  - Does this PR modify or invalidate any of our security controls? **No**.
  - Does this PR store or transmit data that was not stored or transmitted before?  **No**.
- If the answer to any of the questions below is **Yes**, then please add StewGoin as a reviewer, and note that this PR should not be merged unless/until he also approves it.
  - Do you think this PR requires additional review of its security implications for other reasons? **No**.

### What Needs to Be Merged and Deployed Before this PR?

Nothing.

I have gone through and verified that...:

- [X] This PR is reasonably limited in scope, to help ensure that:
  1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
  2. There isn't too much of a burden on reviewers.
  3. Any problems it causes have a small "blast radius".
  4. It'll be easier to rollback if that becomes necessary.
- [X] I have named this PR and its branch such that they'll be automatically be linked to the (most) relevant Jira issue, per: <https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html>.
- [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
- [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
- [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
- [X] Reviews are requested from both:
  - At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
  - Any relevant engineers on other projects (e.g. BFD, SLS, etc.).
- [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
  - Please review the standards every few months to ensure you're familiar with them.

### CODE REVIEW

**Comment by JFU-GIT** [comment]
Following the readme sdk dev, noticed the different behavior python 3.7.13 vs 3.8.10.

with python 3.8 the install went through OK.

However, with python 3.7.13:

Got following error when installing dependencies:
pip install --upgrade pip
pip install -r requirements/req.dev.txt

================== install not completed ===================
Collecting tomli==2.0.1
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting urllib3==1.26.8
  Using cached urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
Collecting importlib-metadata<4.3
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    importlib-metadata<4.3 from https://files.pythonhosted.org/packages/22/51/52442c59db26637681148c21f8984eed58c9db67053a0a4783a047010c98/importlib_metadata-4.2.0-py3-none-any.whl (from flake8==4.0.1->-r requirements/req.dev.txt (line 62))

**Comment by JFU-GIT** [comment]
Probably need to:

either document python versions supported at dev time or

make the requirements compatible for python 3.7 and 3.8 etc.

**Comment by dtisza1** [comment]
> Probably need to:
> 
> either document python versions supported at dev time or
> 
> make the requirements compatible for python 3.7 and 3.8 etc.

@JFU-GIT I think this is OK related to this PR and the SDK release. This sounds related to the BB2 side developer dependencies.

Did the package installation work for you with either Python version?  From a package file and/or TestPyPI?

We may need to setup tests for multiple versions.

**Review by ajshred — APPROVED** [review]
Made some minor readme changes.  Look over them and see if you approve.  Thanks!  Oh, otherwise, this looks great!!!!

**Review by oragame — APPROVED** [review]
Looks good to me! Nice work on this Dave!

**Review by JFU-GIT — APPROVED** [review]
Looks good, good work Dave!

**Comment by JFU-GIT** [comment]
@dtisza1 run into error when installing:


pip install -i https://test.pypi.org/simple/ cms-bluebutton-sdk==0.1.2
Looking in indexes: https://test.pypi.org/simple/
Collecting cms-bluebutton-sdk==0.1.2
  Downloading https://test-files.pythonhosted.org/packages/7e/05/18b99579dcfbae455ef97b3a4c14a8605b8074594f1dc845a1872ebfa472/cms_bluebutton_sdk-0.1.2-py3-none-any.whl (17 kB)
ERROR: Could not find a version that satisfies the requirement pyyaml>=5.0 (from cms-bluebutton-sdk) (from versions: 3.11)
ERROR: No matching distribution found for pyyaml>=5.0

python 3.8.10

**Comment by JFU-GIT** [comment]
(venv) jfuqian@ELL001079:/mnt/c/FORK_CMS_BB2_BFD_DEVLOCAL/BB2-PYTHON-SDK-CONSUME-PYPI$ pip install -i https://test.pypi.org/simple/ cms-bluebutton-sdk==0.1.0
Looking in indexes: https://test.pypi.org/simple/
Collecting cms-bluebutton-sdk==0.1.0
  Downloading https://test-files.pythonhosted.org/packages/02/3c/5ba9cfb3c77bdbfb356cc97b3871537acd9b5037617551f63dfa4e5d2430/cms_bluebutton_sdk-0.1.0-py3-none-any.whl (17 kB)
ERROR: Could not find a version that satisfies the requirement requests-toolbelt>=0.9.1 (from cms-bluebutton-sdk) (from versions: 0.3.1, 0.3.1.post1, 0.4.0)
ERROR: No matching distribution found for requests-toolbelt>=0.9.1

install version 0.1.0 hit other conflicts

**Comment by dtisza1** [comment]
> (venv) jfuqian@ELL001079:/mnt/c/FORK_CMS_BB2_BFD_DEVLOCAL/BB2-PYTHON-SDK-CONSUME-PYPI$ pip install -i https://test.pypi.org/simple/ cms-bluebutton-sdk==0.1.0 Looking in indexes: https://test.pypi.org/simple/ Collecting cms-bluebutton-sdk==0.1.0 Downloading https://test-files.pythonhosted.org/packages/02/3c/5ba9cfb3c77bdbfb356cc97b3871537acd9b5037617551f63dfa4e5d2430/cms_bluebutton_sdk-0.1.0-py3-none-any.whl (17 kB) ERROR: Could not find a version that satisfies the requirement requests-toolbelt>=0.9.1 (from cms-bluebutton-sdk) (from versions: 0.3.1, 0.3.1.post1, 0.4.0) ERROR: No matching distribution found for requests-toolbelt>=0.9.1
> 
> install version 0.1.0 hit other conflicts

@JFU-GIT The main PyPI needs added for the extras like the command below. Does work when trying the specific version install?  

  ```bash
  pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ cms-bluebutton-sdk
  ```

**Pull request merged**
